#!/usr/bin/env python3
"""Validate kit packaging and contracts without external dependencies."""
import argparse
import ast
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
AGENTIC = ROOT / 'agentic'
KIT = AGENTIC / 'kit'
# Set by the installer when validating a staged copy: host docs (AGENTS.md, ...) may
# link to host files that exist in the real project but not in the stage.
HOST_ROOT = Path(os.environ['AGENTIC_HOST_ROOT']) if os.environ.get('AGENTIC_HOST_ROOT') else None
sys.path.insert(0, str(KIT / 'runtime/python'))
from agentic_runtime.registry import SkillRegistry


def packaged_files():
    root_files = ['AGENTS.md', 'CLAUDE.md']
    root_files += [name for name in ['README.md', '.gitignore'] if (ROOT / name).is_file()]
    files = []
    for path in AGENTIC.rglob('*'):
        if not path.is_file() or path.name == '.DS_Store' or path.suffix in {'.pyc', '.pyo'}:
            continue
        rel_parts = path.relative_to(AGENTIC).parts
        if rel_parts[0] == 'data':
            continue
        if any(part in {'__pycache__', 'state', 'artifacts', '.pytest_cache'} or part.startswith('kit.bak-') for part in rel_parts):
            continue
        files.append(path.relative_to(ROOT).as_posix())
    return sorted(root_files + files)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--write-manifests', action='store_true')
    args = parser.parse_args()
    # Include the manifest file even during first generation.
    files = sorted(set(packaged_files()) | {'agentic/MANIFEST.md'})
    if args.write_manifests:
        (AGENTIC / 'MANIFEST.md').write_text('# Manifest\n\nGenerated by `python3 agentic/kit/scripts/validate_structure.py --write-manifests`. Local state, artifacts, caches, and IDE files are excluded.\n\n' + '\n'.join(f'- `{name}`' for name in files) + '\n', encoding='utf-8', newline='\n')
    registry = SkillRegistry(KIT / 'skills')
    skills = registry.discover()
    if not skills:
        raise ValueError('No skills found')
    from agentic_runtime.installation import BEGIN, END
    agents = (ROOT / 'AGENTS.md').read_text(encoding='utf-8')
    fragment = (KIT / 'config/AGENTS.fragment.md').read_text(encoding='utf-8').rstrip()
    if BEGIN not in agents or agents.split(BEGIN, 1)[1].split(END, 1)[0].strip() != fragment:
        raise ValueError('AGENTS.md managed block must match agentic/kit/config/AGENTS.fragment.md')
    config = json.loads((KIT / 'config/skill-registry.json').read_text(encoding='utf-8'))
    caps = json.loads((KIT / 'config/capabilities.json').read_text(encoding='utf-8'))
    permissions = json.loads((KIT / 'config/permissions.json').read_text(encoding='utf-8'))
    allowed_permissions = {'read', 'write_artifact', 'modify_code', 'run_check', 'preview'}
    if set(permissions) != set(skills) or any(not isinstance(p, list) or not p or not set(p) <= allowed_permissions for p in permissions.values()):
        raise ValueError('Each skill needs an explicit valid permission set')
    commands = json.loads((KIT / 'config/allowed-commands.json').read_text(encoding='utf-8'))['commands']
    from agentic_runtime.tools import command_rule
    import shlex
    if not isinstance(commands, list):
        raise ValueError('commands must be an array')
    for command in commands:
        if isinstance(command, str):
            argv = shlex.split(command)
        elif isinstance(command, dict) and set(command) == {'argv', 'permission'}:
            argv = command['argv']
        else:
            raise ValueError('Command rules must contain argv and permission')
        if not isinstance(argv, list) or not argv or any(not isinstance(a, str) or not a for a in argv):
            raise ValueError('Command argv must contain nonempty strings')
        command_rule(shlex.join(argv), [], commands)
    if set(config['eligibility']) != set(skills) or set(caps['defaults']) != set(skills):
        raise ValueError('Registry and capability names must match discovered skills')
    from agentic_runtime.policy import STAGES
    for name, item in skills.items():
        if not item['description'] or not item['stages'] or not set(item['stages']) <= STAGES - {'COMPLETED'}:
            raise ValueError('Invalid description or stage eligibility: ' + name)
        if caps['defaults'][name] not in {f'L{i}' for i in range(7)}:
            raise ValueError('Invalid capability: ' + name)
        if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', name) or len(name) > 64:
            raise ValueError('Invalid skill name: ' + name)
        if f'`{name}`' not in (AGENTIC / 'SKILL-CATALOG.md').read_text(encoding='utf-8'):
            raise ValueError('Skill missing from catalog: ' + name)
    for name in files:
        path = ROOT / name
        if not path.is_file():
            raise ValueError('Missing packaged file: ' + name)
        if path.suffix == '.json':
            json.loads(path.read_text(encoding='utf-8'))
        elif path.suffix == '.py':
            ast.parse(path.read_text(encoding='utf-8'), filename=name)
        elif path.suffix == '.md':
            raw = path.read_text(encoding='utf-8')
            # Literal reusable-kit paths in examples and inline code must exist.
            # Generated project paths and parameterized examples are not sources.
            for match in re.finditer(r'(?<![\w/])agentic/kit/[A-Za-z0-9_./-]+', raw):
                target = match.group(0).rstrip('.')
                if match.end() < len(raw) and raw[match.end()] in '<*{':
                    continue
                if not (ROOT / target).exists():
                    raise ValueError(f'Broken literal kit path in {name}: {target}')
            if re.search(r'(?<![\w/])agentic/(?:skills|templates|config|scripts|workflows|policies)/', raw):
                raise ValueError('Obsolete kit path in ' + name)
            text = re.sub(r'```.*?```', '', raw, flags=re.S)
            for target in re.findall(r'\[[^\]]*\]\(([^\s)]+)\)', text):
                if '://' in target or target.startswith('#'):
                    continue
                relative = target.split('#', 1)[0]
                host_path = HOST_ROOT / path.parent.relative_to(ROOT) / relative if HOST_ROOT else None
                if relative and not (path.parent / relative).exists() and not (host_path and host_path.exists()):
                    raise ValueError(f'Broken local link in {name}: {target}')
    listed = re.findall(r'^- `([^`]+)`$', (AGENTIC / 'MANIFEST.md').read_text(encoding='utf-8'), re.M)
    if listed != files:
        raise ValueError('Stale MANIFEST.md; regenerate manifests')
    print(f'Structure valid: {len(skills)} skills, {len(files)} packaged files')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError) as exc:
        print(str(exc), file=sys.stderr)
        raise SystemExit(1)
