#!/usr/bin/env python3
"""Validate kit packaging and contracts without external dependencies."""
import argparse
import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
KIT = ROOT / 'agentic'
sys.path.insert(0, str(KIT / 'runtime/python'))
from agentic_runtime.registry import SkillRegistry


def packaged_files():
    root_files = ['AGENTS.md', 'CLAUDE.md']
    root_files += [name for name in ['README.md', '.gitignore'] if (ROOT / name).is_file()]
    files = []
    for path in KIT.rglob('*'):
        if not path.is_file() or path.name == '.DS_Store' or path.suffix in {'.pyc', '.pyo'}:
            continue
        if any(part in {'__pycache__', 'state', 'artifacts'} for part in path.relative_to(KIT).parts):
            continue
        files.append(str(path.relative_to(ROOT)))
    return sorted(root_files + files)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--write-manifests', action='store_true')
    args = parser.parse_args()
    # Include the manifest file even during first generation.
    files = sorted(set(packaged_files()) | {'agentic/MANIFEST.md'})
    if args.write_manifests:
        (KIT / 'MANIFEST.md').write_text('# Manifest\n\nGenerated by `python3 agentic/scripts/validate_structure.py --write-manifests`. Local state, artifacts, caches, and IDE files are excluded.\n\n' + '\n'.join(f'- `{name}`' for name in files) + '\n')
    registry = SkillRegistry(KIT / 'skills')
    skills = registry.discover()
    if not skills:
        raise ValueError('No skills found')
    config = json.loads((KIT / 'config/skill-registry.json').read_text())
    caps = json.loads((KIT / 'config/capabilities.json').read_text())
    if set(config['eligibility']) != set(skills) or set(caps['defaults']) != set(skills):
        raise ValueError('Registry and capability names must match discovered skills')
    from agentic_runtime.policy import STAGES
    for name, item in skills.items():
        if not item['description'] or not item['stages'] or not set(item['stages']) <= STAGES - {'COMPLETED'}:
            raise ValueError('Invalid description or stage eligibility: ' + name)
        if caps['defaults'][name] not in {f'L{i}' for i in range(7)}:
            raise ValueError('Invalid capability: ' + name)
        if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', name) or len(name) > 64:
            raise ValueError('Invalid skill name: ' + name)
        if f'`{name}`' not in (KIT / 'SKILL-CATALOG.md').read_text():
            raise ValueError('Skill missing from catalog: ' + name)
    for name in files:
        path = ROOT / name
        if not path.is_file():
            raise ValueError('Missing packaged file: ' + name)
        if path.suffix == '.json':
            json.loads(path.read_text())
        elif path.suffix == '.py':
            ast.parse(path.read_text(), filename=name)
        elif path.suffix == '.md':
            text = re.sub(r'```.*?```', '', path.read_text(), flags=re.S)
            for target in re.findall(r'\[[^\]]*\]\(([^\s)]+)\)', text):
                if '://' in target or target.startswith('#'):
                    continue
                relative = target.split('#', 1)[0]
                if relative and not (path.parent / relative).exists():
                    raise ValueError(f'Broken local link in {name}: {target}')
    listed = re.findall(r'^- `([^`]+)`$', (KIT / 'MANIFEST.md').read_text(), re.M)
    if listed != files:
        raise ValueError('Stale MANIFEST.md; regenerate manifests')
    print(f'Structure valid: {len(skills)} skills, {len(files)} packaged files')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError) as exc:
        print(str(exc), file=sys.stderr)
        raise SystemExit(1)
